version: '3.5'
services:
  qndxx:
    build: .
    container_name: Youth-Learning
    ports:
      - "6106:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - $PWD/dxx:/home/dxx
      - $PWD/img/:/home/dxx/img
      - $PWD/log/:/home/dxx/DxxLog
    tty: true
    networks:
      - net

networks: 
  net: 
    name: proxy_network
    external: true
