version: '3.5'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"

    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
    networks:
      - proxy_network

  proxy_redis:
    image: "redis"
    container_name: proxy_redis
    networks:
      - proxy_network

networks:
  proxy_network:
    name: "proxy_network"
    driver: "bridge"